<?php

namespace AppBundle\Repository;

/**
 * FacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilityRepository extends \Doctrine\ORM\EntityRepository
{
}
