# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.soft_delete_listener:
        class: AppBundle\Events\SoftDeleteListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_listener, event: preSoftDelete }
